version: "3"
services:
  app:
    platform: "linux/amd64"
    image: csanry/text:latest
    build:
      context: ../.
      dockerfile: Dockerfile
    volumes:
      - .././:/project/
    ports:
      - "0.0.0.0:8501:8501"
    command: "/bin/bash -c 'source activate ta22 &&\
    python3 text_analytics/download_nltk.py &&\
    streamlit run app.py --server.address=0.0.0.0 --server.port=8501'"
